config_dir: "{{ root_directory }}/config"

make_directories:
  - { path: ~/.ssh, mode: 700 }
  - { path: ~/.config, mode: 755 }
  - { path: ~/.local, mode: 755 }
    #  - { path: "{{ root_directory }}/.local", mode: 755 }

link_files:
  - { dest: ~/.zshenv, src: config/zsh/.zshenv }
  - { dest: ~/.vimrc, src: config/nvim/init.vim }
  - { dest: ~/.ssh/config, src: config/ssh/config }
#  - { dest: ~/.local/scripts, src: scripts }
#  - { dest: ~/.local/misc, src: misc }
#  - { dest: ~/.local/config,  src: .local/config }
  
