#!/usr/bin/bash

if [[ -n "$WSL_DISTRO_NAME" ]]; then
	_op_cmd="$(wslpath -ua `/mnt/c/Windows/System32/cmd.exe /c echo %USERPROFILE% | tr -d '\r\n'`)/AppData/Local/Microsoft/WinGet/Packages/AgileBits.1Password.CLI_Microsoft.Winget.Source_8wekyb3d8bbwe/op.exe"
	op() {
		$_op_cmd "$@"
	}
fi
