#!/usr/bin/env python3
import os
import subprocess


def copy_to_clipboard(filepath, linenumber, text):
    p = subprocess.Popen(['clipboard', '-i'], stdin=subprocess.PIPE, shell=False)
    p.communicate(text.strip().encode('utf-8'))
    p.terminate()


BINDINGS = {
    'enter': ('execute', '''less "+{linenumber}" "{filepath}"'''),
    # 'enter': ('execute', '''bat --style=plain --theme=zenburn "+{linenumber}" "{filepath}"'''),
    'ctrl-o': ('execute', '''nvim "+{linenumber}" "{filepath}"'''),
    'ctrl-v': ('execute-silent', '''code --reuse-window --goto "`wpath -aw '{filepath}'`:{linenumber}"'''),
    'ctrl-t': ('execute-silent', '''wstart ~/.local/misc/vshelper/openfile.vbs "{filepath}" {linenumber}'''),
    'ctrl-y': ('execute-silent', copy_to_clipboard),
    }

RAW_BINDINGS = {
    #  'ctrl-y': 'execute-silent(echo {} | clipboard -i)',
    }


SHOW_FILEPATH = True
BAT_HIGHLIGHT_THEME = 'zenburn'

# SOURCE_HIGHLIGHTER = os.environ['HOME'] + '/.config/ripsearch/src-highlight.sh'


RG_ARGS = [
    '--ignore-case',
    ]

FZF_ARGS = [
    '-e',
    '--multi',
    '--no-sort',
    '--exit-0',
    '--reverse',
    '--inline-info',
    ]
