- name: make directories
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ make_directories }}"

- name: get config files
  shell: ls {{ config_dir }}
  register: xdg_files

- name: get config/non-xdg files
  shell: ls {{ config_dir }}/non-xdg
  register: non_xdg_files

- name: link to ~/.config
  file:
    src: "{{ config_dir }}/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
  with_items: 
    - "{{ xdg_files.stdout_lines }}"

- name: link to $HOME
  file:
    src: "~/.config/non-xdg/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items: 
    - "{{ non_xdg_files.stdout_lines }}"

- name: link to any path's
  file:
    src: "{{ root_directory }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - "{{ link_files }}"
