#!/usr/bin/env zsh

if type cmd.exe >/dev/null 2>&1; then
	(
		unsetopt bg_nice
		cmd.exe /d /c "$@" | nkf -wu &
		pid=$(( $! - 1 ))
		trap "kill -INT $pid; exit 1" HUP INT QUIT TERM
		while `kill -0 $pid >/dev/null 2>&1`; do done
	)
fi
