[[plugins]]
repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = ['context_filetype.vim']

[[plugins]]
repo = 'tpope/vim-commentary'

# [[plugins]]
# repo = 'scrooloose/nerdcommenter'
# hook_add = '''
# let NERDSpaceDelims=1
# '''

#[[plugins]]
#repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-surround'

#[[plugins]]
#repo = 'thinca/vim-quickrun'
#hook_add = '''
    #let g:quickrun_config = {
    #\   "_" : {
    #\       "hook/time/enable": 1,
    #\       "outputter/buffer/split": ":botright 8sp",
    #\   },
    #\   "cpp/g++" : {
    #\       "cmdopt" : "-std=c++11",
    #\   },
    #\}
#'''

#[[plugins]]
#repo = 'thinca/vim-ref'
#hook_add = '''
#let g:ref_phpmanual_path = $HOME . '/.vim/ref/php-chunked-xhtml'
#'''


# completion

# [[plugins]]
# repo = 'Shougo/neocomplete.vim'
# depends = ['context_filetype.vim']
# if = 'has("lua")'

#[[plugins]]
#repo = 'roxma/nvim-yarp'
#if = '!has("nvim")'

#[[plugins]]
#repo = 'roxma/vim-hug-neovim-rpc'
#if = '!has("nvim")'


# syntax checker

#[[plugins]]
#repo = 'scrooloose/syntastic'
#hook_add = '''
#" let g:syntastic_mode_map = {
            #" \ 'mode': 'active',
            #" \ 'active_filetypes': [],
            #" \ 'passive_filetypes': ['python']
            #" \}
#let g:syntastic_python_checkers = ['pyflakes', 'pep8']
#'''
