#!/usr/bin/env zsh

newpath=()
script_dir=$(cd `dirname $0` && pwd -P)

for p in $path; do
	if [ ! "$script_dir" = "$p" ]; then
		newpath+=($p)
	fi
done

# GTAGSLIBPATH=
# GTAGSROOT=
# GTAGSDBPATH=

cmd=(`echo ${^newpath}/global(N)`)

current_dir=`pwd`
while [ ! "$current_dir" = "/" ]; do
	if [ -x "$current_dir/.globalrc" ]; then
		GLOBALBIN=${cmd[1]} "$current_dir/.globalrc" "$@"
		exit $?
	fi
	current_dir="`dirname $current_dir`"
done

${cmd[1]} "$@"
