#!/usr/bin/env zsh
set -e

unsetopt bg_nice

HELPER_DIR="$(cd `dirname $0` && pwd -P)/../misc/uehelper"

invoke() {
	if ! which fab >/dev/null 2>&1; then
		pip3 install fabric
	fi
	local current_dir=$(pwd -P)
	(cd $HELPER_DIR && TARGET_DIR="$current_dir" python3 $HELPER_DIR/fabfile/bin/ue "$@")
}

case "$1" in
	configure)
		shift
		invoke projectfiles "$@"
		# invoke supportfiles "$@" &
		;;
	uat)
		invoke "$@"
		;;
	build|rebuild|clean)
		invoke "$@"
		;;
	cook|lighting|package|deploy|cmdline|addcmdline|editor|command)
		invoke "$@"
		;;
	log-parse)
		invoke log_parse "$@"
		;;
	update)
		invoke "$@" &
		;;
	test)
		invoke "$@" &
		;;
	*)
		exec $0 editor "$@"
		;;
esac
