- name: Update brew
  homebrew:
    update_homebrew: yes

- name: Upgrade brew
  homebrew:
    upgrade_all: yes

- name: Install homebrew formulas
  homebrew: 
    name: "{{ brew_formulas }}"
  ignore_errors: true
