- name: make vscode settings directory
  file:
    path: "{{ osx_vscode_settings_path }}"
    state: directory

- name: link to vscode setting files
  file:
    src: "~/.config/vscode/{{ item }}"
    dest: "{{ osx_vscode_settings_path }}/{{ item }}"
    state: link
  with_items:
    - "{{ vscode_settings }}"

- name: Setup Finder
  shell: >
    # show dotfiles
    defaults write com.apple.finder AppleShowAllFiles TRUE
    defaults write com.apple.desktopservices DSDontWriteNetworkStores TRUE
    killall Finder
